// ============================================================
//  SSLEQAudioProcessor.h  — JUCE AudioProcessor wrapper
//  Drop this into a JUCE project as the main PluginProcessor
// ============================================================
#pragma once

// Uncomment when building inside JUCE:
// #include <JuceHeader.h>
// #include "SSLEQPlugin.cpp"

/*
──────────────────────────────────────────────────────────────
  JUCE AudioProcessor implementation skeleton.
  Paste this into your PluginProcessor.h / .cpp generated by
  JUCE's Projucer or CMake template.
──────────────────────────────────────────────────────────────

class SSLEQAudioProcessor  : public juce::AudioProcessor
{
public:
    SSLEQAudioProcessor()
        : AudioProcessor (BusesProperties()
            .withInput  ("Input",  juce::AudioChannelSet::stereo(), true)
            .withOutput ("Output", juce::AudioChannelSet::stereo(), true))
    {
        // Register parameters
        for (int i = 0; i < kNumParams; i++) {
            double defaultNorm = (i == kOutputGain) ? outputToNorm(0.0) : eqToNorm(0.0);
            addParameter(new juce::AudioParameterFloat(
                juce::ParameterID { PARAM_NAMES[i], 1 },
                PARAM_NAMES[i],
                juce::NormalisableRange<float>(0.0f, 1.0f),
                (float)defaultNorm
            ));
        }
    }

    ~SSLEQAudioProcessor() override = default;

    // ── Lifecycle ────────────────────────────────────────────
    void prepareToPlay(double sampleRate, int samplesPerBlock) override {
        plugin.prepareToPlay(sampleRate, samplesPerBlock);
    }

    void releaseResources() override {
        plugin.resetDSP();
    }

    bool isBusesLayoutSupported(const BusesLayout& layouts) const override {
        auto stereo = juce::AudioChannelSet::stereo();
        return layouts.getMainInputChannelSet()  == stereo
            && layouts.getMainOutputChannelSet() == stereo;
    }

    // ── DSP ──────────────────────────────────────────────────
    void processBlock(juce::AudioBuffer<float>& buffer,
                      juce::MidiBuffer&) override
    {
        // Sync parameters from host
        auto** params = getParameters().begin();
        for (int i = 0; i < kNumParams; i++)
            plugin.setParameter(i, ((juce::AudioParameterFloat*)params[i])->get());

        // Process stereo
        float* L = buffer.getWritePointer(0);
        float* R = buffer.getWritePointer(buffer.getNumChannels() > 1 ? 1 : 0);
        plugin.processBlock(L, R, buffer.getNumSamples());
    }

    // ── Editor ───────────────────────────────────────────────
    juce::AudioProcessorEditor* createEditor() override {
        return new SSLEQEditor(*this);   // implement in SSLEQEditor.h
    }
    bool hasEditor() const override { return true; }

    // ── Info ─────────────────────────────────────────────────
    const juce::String getName() const override { return "SSL EQ"; }
    bool   acceptsMidi()  const override { return false; }
    bool   producesMidi() const override { return false; }
    double getTailLengthSeconds() const override { return 0.0; }

    // ── Programs ─────────────────────────────────────────────
    int  getNumPrograms()    override { return 1; }
    int  getCurrentProgram() override { return 0; }
    void setCurrentProgram(int) override {}
    const juce::String getProgramName(int) override { return "Default"; }
    void changeProgramName(int, const juce::String&) override {}

    // ── State ────────────────────────────────────────────────
    void getStateInformation(juce::MemoryBlock& dest) override {
        juce::MemoryOutputStream stream(dest, true);
        for (int i = 0; i < kNumParams; i++)
            stream.writeDouble(plugin.getParameter(i));
    }

    void setStateInformation(const void* data, int size) override {
        juce::MemoryInputStream stream(data, (size_t)size, false);
        for (int i = 0; i < kNumParams; i++) {
            double v = stream.readDouble();
            plugin.setParameter(i, v);
        }
    }

    // Expose for editor frequency response drawing
    double getMagnitude(double freq) const { return plugin.getMagnitude(freq); }

private:
    SSLEQPlugin plugin;
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(SSLEQAudioProcessor)
};
*/
